### ISSUE TITLE
Releases out of sync

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-mobile-app-security#73]
The content in this repo seems to talk about 1.4.2 when 1.5.0 is the latest?

While https://github.com/OWASP/owasp-mastg/releases doesn't seem to have any release 1.4.2 at all.

**Comment by cpholguera** [comment]
Hi @kingthorin, where exactly have you found a reference to a version 1.4.2 of the MASTG? 

The latest version of the MASTG is v1.5.0.

Version 1.4.2 only exists for the MASVS. But today we released v1.5.0.

**Comment by kingthorin** [comment]
It's been fixed.
https://web.archive.org/web/20221225065620/https://owasp.org/www-project-mobile-app-security/

![image](https://user-images.githubusercontent.com/7570458/215776906-5f8ed4dc-f27f-437b-b582-a2cdf1a4c1c0.png)

**Comment by kingthorin** [comment]
I was probably also mingling the details of the two docs 😢
